//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeinteenFlower.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrHeader
    {
        public int TransactionID { get; set; }
        public int MemberID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public decimal DiscountPercentage { get; set; }
    
        public virtual MsMember MsMember { get; set; }
        public virtual TrDetail TrDetail { get; set; }
    }
}
